development:
  adapter: postgresql
  database: video-page_development
  host: localhost
  username: diegocohen

production:
  adapter: postgresql
  database: video-page_development
  host: localhost
  username: diegocohen